### ISSUE TITLE
Artboard (export/import selected artboard)

### ISSUE THREAD

**Issue by danielmeloalencar** [easylogic/editor#100]
Before redoing the timeline, I think that another essential feature would be to be able to export the selected artboard (as a component) and also to be able to import it into the current artboard.
It is extremely easy to implement and extremely useful.
Thank you!

**Comment by easylogic** [comment]
@danielmeloalencar 

Ok, good idea. 

I feel like I need it too. 
However, the editor now does not have a storage structure. 
If it is in a cloud format, it would be possible to store components immediately, but currently, we do not have a separate plan for the cloud.

If you have any ideas for export/import, I would like to share them with you.

Currently, the function of exporting and importing the entire project as JSON is implemented.

The artboard is not individual.

**Comment by danielmeloalencar** [comment]
Could be on localstorag

**Comment by easylogic** [comment]
Ok, I understand. 

I'll create a structure that stores only artboards in localStorage.

**Comment by danielmeloalencar** [comment]
Thank you

**Comment by easylogic** [comment]
Due to the blob capacity such as image, it is currently implementing as IndexedDB.

**Comment by danielmeloalencar** [comment]
Perfect!
