### ISSUE TITLE
Feature Request - Icon Library Support

### ISSUE THREAD

**Issue by billiemead** [easylogic/editor#111]
Hi, as the title suggests I was wondering if you planned on offering Font Awesome, Line Awesome,  etc. icon library support?

Cheers,
Billie

**Comment by easylogic** [comment]
hi @billiemead 

Although not currently available, I will be able to obtain external resources when the basic functions of the editor are completed.

Thank you.

**Comment by billiemead** [comment]
@easylogic 
I can't wait. BTW, thank you for such an amazing graphics tool. I am just learning how to really use it and it's very complete. 

Do you have a public roadmap anywhere? 

Cheers!

**Comment by easylogic** [comment]
@billiemead 

It's still not enough, but thank you for saying it in a good way.

Currently, I think there are three basic roadmaps for this year.

1. Vector editing similar to Figma
2. Implement Timeline that can properly express Animation
3. Cloud Beta Service with google login.

If you have a nice feature you think of, you can give me a feature request.

**Comment by easylogic** [comment]
@billiemead 

I added open source icon like layer.

you can use it on site (with v0.10.8) 



https://user-images.githubusercontent.com/591983/111077008-2d4fde00-8532-11eb-9e06-b25ece774bc6.mp4

**Comment by billiemead** [comment]
@easylogic 
what amazing news. I will pull down 0.10.8 tonight.
Keep up the great work and thanks for letting me know!
