### ISSUE TITLE
Feature Request - hold shift key to constrain Object while Rotating 

### ISSUE THREAD

**Issue by billiemead** [easylogic/editor#114]
@easylogic 

Similar to previous request to lock Aspect Ratio with a modifier key...

When rotating an object and holding down Shift (or other modifier) key, the angle would snap to 15 degree increments.

I mention these as drawing with a mouse is difficult enough and these helpers are taken straight from Illustrator, Photoshop, etc.

Cheers ~

**Comment by easylogic** [comment]
hi @billiemead 

ok, I understood.

I will add this feature in next release.

Thank you.

**Comment by easylogic** [comment]
@billiemead  

I released degree snap with shift key.  

You can use it on site.
