### ISSUE TITLE
Technologies used

### ISSUE THREAD

**Issue by Clientik** [easylogic/editor#118]
Hi) I am a student from Russia and on a study assignment I need to write my own editor similar to yours. The functionality of your editor is very good and excellent, but unfortunately I need to write it using the VUE framework. You can tell what technologies and frameworks you mainly used when creating your awesome tool. The most difficult thing I faced was writing an endless canvas, unfortunately my knowledge is not enough to build such a complex structure. Thank you for your attention and the fastest answer.
If possible, I would like to chat with any messengers, I have a lot of questions)

**Comment by easylogic** [comment]
hi @Clientik 

Thank you for your interest in the project.

The editor was built on its own without using other framework(react or vue or angular). 
The reason for doing this is to focus on the editor itself.

Implementing a never-ending canvas is not difficult.

You just need to understand the geometry used by the browser.(https://www.w3.org/TR/css-transforms-1/)

This feature is call panzoom. 

If you use vue, a project like https://github.com/thecodealer/vue-panzoom can help.

However, if you have the goal of actually creating the entire editor, you may have to implement Geometry functions internally.

There is a blog about some of the features I used while creating the editor. However, this is in Korean.

https://easylogic.medium.com/%EA%B0%9C%EB%B0%9C%EC%9E%90-%ED%8A%B8%EB%A0%8C%EB%93%9C%EB%A5%BC-%EB%B2%84%EB%A6%AC%EB%8B%A4-2%EB%85%84%ED%9B%84-%EC%86%8C%EA%B0%90-a0d9809588b3

**Comment by Clientik** [comment]
Thank you, you helped me a lot.  It's even difficult to assess.  If I have any more questions, can I contact you personally? For example, in messengers ...

**Comment by easylogic** [comment]
https://join.slack.com/t/easylogicstudio/shared_invite/zt-pnatchgk-XdL3OjRFk0eAi4cgaOveFQ 

I made a slack channel. 

I think we can talk here.
