### ISSUE TITLE
뷰포트 화면에서 컨텍스트 메뉴를 열고 닫으면 mousemove 이벤트가 그대로 호출됩니다.

### ISSUE THREAD

**Issue by redgoose-dev** [easylogic/editor#119]
뷰포트에서 요소를 선택하고 이동하거나 사이즈를 바꾸는중에 컨텍스트 메뉴를 열고 빈공간을 눌러서 닫으면 드래그 되어있는 상태로 움직여 집니다.

뷰포트 빈 화면에서 컨텍스트 메뉴를 열고 닫으면 마우스 버튼을 누르지도 않았는데 선택이 되어있는 현상이 생깁니다.

![Apr-27-2021 11-38-19](https://user-images.githubusercontent.com/1978100/116176456-24674480-a74d-11eb-96c2-84aa21ee33b9.gif)

작동 화면

**Comment by easylogic** [comment]
아 ~ 그러네요. ^^ 마우스 클릭 할 때 타입에 따라 분리 시켜야겠습니다. 

확인 감사합니다.  ^^

**Comment by redgoose-dev** [comment]
오늘 작업하면서 테스트하다가 발견한 현상이라서 금방 알게됐어요. ㅎㅎ
`contextmenu`이벤트 일으켜서 다른 마우스 이벤트를 막는 방법도 있을거예요. :)

**Comment by easylogic** [comment]
@redgoose-dev  코드 수정했습니다. 기능 확인 한번 해주세요.

**Comment by redgoose-dev** [comment]
@easylogic 제가 모든 마우스 이벤트에서 문제가 있다는것을 적지 않은게 잘못이었네요. ㅠㅠ

![mousemove-bug-002](https://user-images.githubusercontent.com/1978100/116330818-43c3a780-a809-11eb-8372-5b3324c8e21c.gif)

처음에 제가 박스를 만들고 사이즈를 변경하거나 위치를 옮기다가 발견한 버그였어요. 아마도 mousemove 이벤트가 들어가 있으면 이런 현상을 발견할 수 있을거예요. ㅠㅠ

**Comment by easylogic** [comment]
@redgoose-dev 

마우스를 안 쓰다 보니 다시 체크 해봐야겠네요.  ^^ 확인 감사합니다.

**Comment by easylogic** [comment]
전체 마우스 이벤트 다시 조정했습니다.  감사합니다. ^^
