### ISSUE TITLE
ClipPath 

### ISSUE THREAD

**Issue by danielmalencar** [easylogic/editor#121]
ClipPath inset mode dont works
![image](https://user-images.githubusercontent.com/25048796/120872166-3d48ee00-c574-11eb-9e0d-1b3f1a74707b.png)

**Comment by danielmalencar** [comment]
Browsers Firefox and Google Chrome on Ubuntu 21.04

**Comment by easylogic** [comment]
Thanks for your reporting. 

I checked it .

**Comment by easylogic** [comment]
I released new version (v0.10.19) . 
Please try to it.
