### ISSUE TITLE
Interface problem

### ISSUE THREAD

**Issue by danielmalencar** [easylogic/editor#122]
Interface problem on click Draw Tool and Path Tool
![image](https://user-images.githubusercontent.com/25048796/120872290-a29cdf00-c574-11eb-8cd9-ce8890398cc5.png)

**Comment by easylogic** [comment]
Thanks, @danielmalencar.

I checked it.

**Comment by easylogic** [comment]
I released new version (v0.10.19) . 
Please try to it.
