### ISSUE TITLE
Delete shortcut

### ISSUE THREAD

**Issue by danielmalencar** [easylogic/editor#124]
Delete shortcut (backspace) dont works. And the ideal would be the DELETE key. It's more intuitive.

**Comment by easylogic** [comment]
thanks for your reporting.  

I'll check again and let you know.

**Comment by easylogic** [comment]
I fixed this issue. 

Backspace Key and Delete  Key are all support.

Please test it again.

**Comment by danielmalencar** [comment]
Very good!
