### ISSUE TITLE
Failed to compile Ubuntu 20.10 (popOS)

### ISSUE THREAD

**Issue by danielmalencar** [easylogic/editor#125]
![image](https://user-images.githubusercontent.com/25048796/121093976-3d3f2d00-c7c4-11eb-8ae5-d2f304ef22e6.png)
Steps to reproduce:
git clone https://github.com/easylogic/editor
cd editor
npm install
npm run dev

with and without root user.

**Comment by easylogic** [comment]
I checked it. 

I'll fix it and let you know

**Comment by easylogic** [comment]
I modifed this issue.  

please clone it again.

**Comment by danielmalencar** [comment]
Thank you!
