### ISSUE TITLE
Path, Draw tools, etc.. moving problem

### ISSUE THREAD

**Issue by ghost** [easylogic/editor#126]
It is very  very very difficult to move any drawing created with the SVG tools with the mouse.

**Comment by easylogic** [comment]
I agree too. Currently, the only development equipment is the MacBook Pro. 
So I didn't use the mouse. 
I will continue to improve the pattern of using the mouse.

**Comment by easylogic** [comment]
Hi @danielmalencar.

I want to hear your impressions about the editor I'm making, so I'm leaving a message.

I'm making a web design tool, but I don't really use it anywhere.

Currently, it is in the beginning stage, so there is no clear direction.

The ultimate goal is a tool like Figma, but realistically, it seems difficult right now to catch up with that tool alone.

I am trying to grasp the direction of the tool in detail once.

So, I'd like to hear your impressions of using the tool.
