### ISSUE TITLE
Electronjs

### ISSUE THREAD

**Issue by ghost** [easylogic/editor#127]
How to build the pure electron version?

**Comment by easylogic** [comment]
It was there in the past, but it is not now. I'll try the Electron build again and tell you.

**Comment by easylogic** [comment]
I found how to run editor on electron.  
I'll update the code and let you know again.

**Comment by danielmalencar** [comment]
Thank you!

> I found how to run editor on electron.
> I'll update the code and let you know again.

**Comment by easylogic** [comment]
https://github.com/easylogic/editor#development---electron 

This is an way that run on electron. 

Currently, you can only test locally.

The distribution seems to require a little more thought.
