### ISSUE TITLE
Artboards and custom components

### ISSUE THREAD

**Issue by danielmalencar** [easylogic/editor#128]
Currently, the Artboard Assets feature also allows you to add individual components and not just complete Artboards.
I believe that it would be correct to treat artboards as Pages or Screens, in other words, in this case, allow saving only the complete Artboard.

In the Custom Components tab, you could have the same + button to add the individual components and their children.

Basically it would be splitting the Artboard Arts feature in two, one for Artboards and one for Components (as in the screenshot). It would look amazing.
![image](https://user-images.githubusercontent.com/25048796/121112082-4e009a80-c7e6-11eb-912c-27b503d2fe0f.png)

**Comment by easylogic** [comment]
@danielmalencar 

wow that's a great idea. ^^ I'll try to implement it as much as possible.

**Comment by easylogic** [comment]
hi @danielmalencar  

I released new version.  

It support to add custom component like artboard assets.  

<img width="344" alt="스크린샷 2021-06-14 오전 2 28 03" src="https://user-images.githubusercontent.com/591983/121816724-2fa01080-ccb8-11eb-8c18-edbf4977d27a.png">

The design will be revised.

**Comment by danielmalencar** [comment]
@easylogic Perfect!

**Comment by easylogic** [comment]
@danielmalencar 

The basic pattern is the same as the logic saved in the artboard. 
Please let me know if you find anything strange while using it.

**Comment by danielmalencar** [comment]
@easylogic  For now it's perfect.

**Comment by easylogic** [comment]
I modified component list design.
