### ISSUE TITLE
Adding icon with object selected does not move

### ISSUE THREAD

**Issue by Correct-Syntax** [easylogic/editor#129]
![Screenshot 2021-06-09 110657](https://user-images.githubusercontent.com/60711001/121390344-e72ccf80-c912-11eb-8d92-582afbbafe37.png)

If an object is selected when adding an icon from the left panel, when I go to move it, the blue border moves but not the icon (in the above image the "comment" icon should be moved where the blue border widget thing is.

**Comment by easylogic** [comment]
hi @Correct-Syntax  

Thanks for reporting. 

To verify this, I need some information.

Can you check the browser you are using and if there are any script errors?

**Comment by Correct-Syntax** [comment]
This is on Firefox (the latest)

Errors: [console-export-2021-6-9_13-5-57.txt](https://github.com/easylogic/editor/files/6625958/console-export-2021-6-9_13-5-57.txt)

**Important note:** it seems this is only a problem when the Layout is set to GRID

**Comment by easylogic** [comment]
I am checking the error code you showed.

I'll check some more and let you know.

**Comment by easylogic** [comment]
@Correct-Syntax 

I released new version. 

Please try it to test.   (https://editor.easylogic.studio)

**Comment by Correct-Syntax** [comment]
![Screenshot 2021-06-13 173938](https://user-images.githubusercontent.com/60711001/121817012-79e7aa00-cc44-11eb-8807-96ae31618ba3.png)

Still seems to be an issue.

**Exact steps**:
1. Select default rectangle and set layout to GRID
2. Add icon from "Library"
3. Try to move the icon

The only error is:

```
Uncaught (in promise) TypeError: this.el.getAttribute is not a function
    value https://editor.easylogic.studio/editor.js?32db23a777e4b47937eb:1
    value https://editor.easylogic.studio/editor.js?32db23a777e4b47937eb:1
    value https://editor.easylogic.studio/editor.js?32db23a777e4b47937eb:330
    value https://editor.easylogic.studio/editor.js?32db23a777e4b47937eb:1
```

**Comment by easylogic** [comment]
hi @Correct-Syntax  

This is a matter of the functionality of the editor itself. 
It may look like a bug.

The grid layout itself subordinates child items to their parent.

That's why, in fact, it becomes impossible to move by dragging.

However, there is a problem that selection must be maintained as it is.

I need to think a bit more about usability.

**Comment by Correct-Syntax** [comment]
Okay. Yes, I had that thought, but it would seem like a bug to an unsuspecting user. 😆

**Comment by easylogic** [comment]
hi @Correct-Syntax 

Layout items are prevented from moving after selection.

please test it again.

**Comment by Correct-Syntax** [comment]
Much better now 👍

**Comment by easylogic** [comment]
Good.  

 If you need any features, please let me know. 
I will do my best to make it.

**Comment by easylogic** [comment]
hi @Correct-Syntax. 

I'd love to hear your impressions of using the tool.

I think this will help a lot in determining the direction the tool should go.

**Comment by Correct-Syntax** [comment]
Hi @easylogic,

While this is a neat project, I haven't really actually used it too much so I am not sure how well my feedback would be. I mostly use Sketch for Windows in my real and hobby work since I am familiar with it. 

It's not really clear, but does this project intend to replace Sketch? I think you had mentioned it was something similar.

Just a laundry-list of features and improvements that would be nice (just based on my fiddling around with the editor):

- drag n' drop icons, etc from the library to the viewport
- make the cursors to look a lot better (right now they are fuzzy, too large in my opinion and look horrible overall....)
- style the controls a bit more so that it's not left up to the OS to make a mess of the styling (esp. on Windows)

Also, I have considered helping with the project, but I would really prefer to work with Vue.js...so maybe you could convert the project into a Vue.js based one rather than vanilla js? (Easier said than done, of course...!)

**Comment by easylogic** [comment]
hi @Correct-Syntax  

Thank you so much for your comments.

I will try to reflect it as much as possible.

It is right that the goal of the tool itself is to become a professional design tool like sketch or figma.

But I guess I'm still in the experimental stage.

And now I'm getting ready to put the editor in the form of a component elsewhere as well. 
So I think I will be able to make a wrapper for vuejs in the near future.
