### ISSUE TITLE
Q: How can I use editor

### ISSUE THREAD

**Issue by TroyTae** [easylogic/editor#182]
Hello I found this repo while looking for suitable tool for UI automation

I wanna test this editor but it seems web page isn't deployed
(https://editor-core.easylogic.studio/)

How can I use it?

Thank you :)

**Comment by easylogic** [comment]
hi @TroyTae 

please use this link. 

https://editor.easylogic.studio/ 

ps. 

I should check  for editor-core site;

**Comment by TroyTae** [comment]
Thank you!
