### ISSUE TITLE
Weird position when keyframe animation

### ISSUE THREAD

**Issue by j2l** [easylogic/editor#51]
Sorry, another glitch :smile_cat: 
Following your documentation, I tried the keyframe animation and there are 2 problems:
![editor_blank](https://user-images.githubusercontent.com/65325/83274931-bded4580-a1ce-11ea-8c0c-4fa68ce518e7.png)

As you can see, location of the block is outside its selector.

And also, when I close the CSS Animation panel and re-open it, it looses the keyframe "sample" to get back to "select a keyframe". But, if you don't change the keyframe identifier, it keeps the right keyframe. So it's more a cosmetic detail.

**Comment by j2l** [comment]
Adding another Art board, then going back to it fixes the first problem. But you can't delete the second Art board.
I noted that keyframe also reset `width` properties after re-opening it.

**Comment by easylogic** [comment]
@j2l 
I fixed this issue.   

please try to run at master branch.
