### ISSUE TITLE
Editor is not defined

### ISSUE THREAD

**Issue by j2l** [easylogic/editor#53]
When clicking Timeline, then "+" near Animation, the console states:
```
main.893893d34eecc358bf25.js?__WB_REVISION__=684307f98dd2060686018e8ea9c0b3a3:1 Uncaught (in promise) ReferenceError: editor is not defined
    at Object.execute (main.893893d34eecc358bf25.js?__WB_REVISION__=684307f98dd2060686018e8ea9c0b3a3:1)
    at Object.o (main.893893d34eecc358bf25.js?__WB_REVISION__=684307f98dd2060686018e8ea9c0b3a3:1)
    at main.893893d34eecc358bf25.js?__WB_REVISION__=684307f98dd2060686018e8ea9c0b3a3:1
    at Array.forEach (<anonymous>)
    at main.893893d34eecc358bf25.js?__WB_REVISION__=684307f98dd2060686018e8ea9c0b3a3:1
```
![timeline_editor not defined](https://user-images.githubusercontent.com/65325/83281755-db271180-a1d8-11ea-976b-1bcc44031018.png)

Also image links are not working in the doc about timeline, like https://www.easylogic.studio/docs/timeline/time-control.html

Or it's not ready for primetime :smile_cat: 

Have a great day!

**Comment by j2l** [comment]
Sorry, I finally understand the logic and keyframes are showing on the timeline.

**Comment by easylogic** [comment]
@j2l 
I fixed this issue.   

please try to run at master branch.
