### ISSUE TITLE
 Support customizable shortcut command

### ISSUE THREAD

**Issue by easylogic** [easylogic/editor#59]
## 기본 
 
* [x]  [ 기본 선택 ] : V - select view 
* [x] [ 사각형 ] : R, M - add Rect 
* [x] [ 원형 ] : O, L - add Circle 
* [x] [ 텍스트 ] : T - add Text
* [x] [ 펜툴 ] : P - add SVG Path
* [x] [ 브러쉬(draw) ] : B - add SVG Path by drawing 
* [x] [ 아트보드 ] : A - select Artboard
* [x] [ 레이어를 위로 올릴 때 ] : ctrl + ]- move layer to above
* [x] [ 레이어를 아래로 내릴 때 ] : ctrl + [ - move layer to below
* [x] [ 객체 삭제] :  Backspace or Shift + Backspace  -  delete selected items 

## 그룹 (Group)

* [x] 윈도우 : ctrl + G
* [x] 맥 : command + G 

## 그룹해제  (Ungroup)
* [x] 윈도우 : ctrl + shift + G
* [x] 맥 : command + shift + G

**Comment by j2l** [comment]
Hello, 
[ is ALTGR+5 on a French AZERTY keyboard. Not sure it will work with ctrl+altgr+5.
I think there's a "common" list of keyboard shortcuts somewhere to prevent all changing keys.

**Comment by easylogic** [comment]
@j2l   i agree with you.  

I will make main keyboard command list.  

I still have only plans.

**Comment by easylogic** [comment]
@wfedev 단축키를 거의 다 맞춘 것 같아요.
