### ISSUE TITLE
Export animation don't works

### ISSUE THREAD

**Issue by danielmalencar** [easylogic/editor#69]
Error:
this.artboard.getSelectedTimelineLastTime is not a function
![ERRo 2020-09-04 154613](https://user-images.githubusercontent.com/25048796/92275640-d81d7a80-eec5-11ea-98e7-2ad8980bf83f.png)

**Comment by danielmalencar** [comment]
Apparently he is trying to get the current Artboard timeline, but the timeline belongs to the project and not to Artboard

**Comment by danielmalencar** [comment]
Solve changing 

 var js = AnimationExport.generate(artboard, 'anipa')
to 
 var js = AnimationExport.generate(project, 'anipa')

in **ExportManager.js**

**Comment by danielmalencar** [comment]
But it doesn't make much sense for the timeline to be part of the project, it should belong to Artboard

**Comment by easylogic** [comment]
hi @danielmalencar  

Thanks for your reporting. 

I fixed it now.  

please refresh to https://editor.easylogic.studio
