### ISSUE TITLE
Opacity keyframe error

### ISSUE THREAD

**Issue by danielmalencar** [easylogic/editor#70]
When adding opacity keyframes starting with zero and repeating another zero, opacity always starts with 1 on play

![error-Opacity](https://user-images.githubusercontent.com/25048796/92296817-f9568900-ef0e-11ea-89f3-2ba05587d34d.png)

**Comment by easylogic** [comment]
I will try to test it.

**Comment by easylogic** [comment]
i found a problem.

**Comment by danielmalencar** [comment]
Where?

**Comment by easylogic** [comment]
opacity is not zero. it is undefined.

i will fix it.

**Comment by danielmalencar** [comment]
Thanks

**Comment by danielmalencar** [comment]
I believe the same thing happens with rotation

**Comment by danielmalencar** [comment]
I would like to collaborate, how to proceed?

**Comment by easylogic** [comment]
@danielmalencar  

I have a plan for collaborate system.  
I am preparing to apply CRDT Sytem that is Yorkie(https://github.com/yorkie-team/yorkie)

So I am refactoring editor command  for collaborate system.

**Comment by easylogic** [comment]
@danielmalencar 

Currently, the editor is making it alone. 

I am trying to make a function that can go to simultaneous editing by applying the CRDT system internally. 

I am currently refactoring for that.

Do you have any features you want in the editor?

**Comment by danielmalencar** [comment]
I would just like you to leave the timeline working 100%, first of all

**Comment by danielmalencar** [comment]
There is an error in the timeline when adding a rotate keyframe

**Comment by easylogic** [comment]
@danielmalencar 

I fixed a rotate issue.  

Please test it. 

Thank you.

**Comment by danielmalencar** [comment]
Now its works. Thank you

**Comment by danielmalencar** [comment]
> When adding opacity keyframes starting with zero and repeating another zero, opacity always starts with 1 on play
> 
> ![error-Opacity](https://user-images.githubusercontent.com/25048796/92296817-f9568900-ef0e-11ea-89f3-2ba05587d34d.png)

But this problem with opacity remains

**Comment by easylogic** [comment]
@danielmalencar  

There was a bug in css output. Thanks for letting me know

I fixed it now, so try again

**Comment by danielmalencar** [comment]
Now it's working. But why the bug tag? What's not working?

**Comment by easylogic** [comment]
It's just a sign that you fixed the bug. Do not worry too much. ^^
