### ISSUE TITLE
Path editing dont works

### ISSUE THREAD

**Issue by danielmalencar** [easylogic/editor#73]
![Captura de tela 2020-09-15 230318](https://user-images.githubusercontent.com/25048796/93284743-abad0c80-f7a9-11ea-8aba-d90c1709ae49.png)

After I create a path, the edits have no effect

**Comment by easylogic** [comment]
hi @danielmalencar  

Thanks for your reporting. 

I will check it.

**Comment by easylogic** [comment]
@danielmalencar 

I fixed this problem.

Please test it again.

**Comment by danielmalencar** [comment]
Perfect. Thank you
