### ISSUE TITLE
LOCK LAYER BUTTON BUG

### ISSUE THREAD

**Issue by danielmalencar** [easylogic/editor#76]
Hi!
When clicking on the lock icon the layer does not lock immediately, it is necessary to make some object selection in Artboard.

Lock icon does not change when clicking, same with eye icon (visible / invisible).

![Captura de tela 2020-09-21 205352](https://user-images.githubusercontent.com/25048796/93832752-041e5700-fc4d-11ea-9c3c-ef5ef8152c34.png)

**Comment by easylogic** [comment]
hi @danielmalencar  

Thanks for your reporting. 

I checked it. 

I will fix it and let me know to you.

**Comment by easylogic** [comment]
I fixed it now. 

please try to test again.

**Comment by danielmalencar** [comment]
Now works!
