### ISSUE TITLE
Project name and description dont save

### ISSUE THREAD

**Issue by danielmalencar** [easylogic/editor#77]
When filling in the project information, it is not saved

![Captura de tela 2020-09-21 210025](https://user-images.githubusercontent.com/25048796/93832949-9c1c4080-fc4d-11ea-970e-e5cd30a9274d.png)

**Comment by easylogic** [comment]
Hi @danielmalencar. 

Thanks for looking for me carefully.  

I will fix it.

**Comment by easylogic** [comment]
I fixed it now. 

please try to test again.

**Comment by danielmalencar** [comment]
Thanks!
