### ISSUE TITLE
Project Selection 

### ISSUE THREAD

**Issue by danielmalencar** [easylogic/editor#78]
Hello!
I found another bug, it happens when you try to select a project from the list. He loads the project normally, but does not have feedback from the selection to the user.
It does not have the selection effect.

![Captura de tela 2020-09-22 112510](https://user-images.githubusercontent.com/25048796/93895674-797a3e00-fcc6-11ea-8ec8-e696bb294897.png)

**Comment by easylogic** [comment]
hi @danielmalencar 

I found it too. 

I am fixing it.

**Comment by easylogic** [comment]
I fixed it now. 

please try to test again.

**Comment by danielmalencar** [comment]
Perfect
