### ISSUE TITLE
Bug on move Path

### ISSUE THREAD

**Issue by danielmalencar** [easylogic/editor#79]
Problem when trying to move the Path Objects by clicking on its name. 

![Captura de tela 2020-09-27 125544](https://user-images.githubusercontent.com/25048796/94369582-fc353b80-00c0-11eb-9cc5-2bc374f0564e.png)

**Comment by easylogic** [comment]
I checked this issue. 

I will fix it today.

**Comment by easylogic** [comment]
I fixed this problem. 

Please test it again.

**Comment by danielmalencar** [comment]
Now its works. Thank you.
