### ISSUE TITLE
BUG: Path back to its initial shape

### ISSUE THREAD

**Issue by danielmalencar** [easylogic/editor#80]
After editing any Path Object, moving it back to its initial shape.

Steps to reproduce:
- Add any Path Object (circle, rectangle).
- Double click to edit your paths.
- Finish editing.
- Move the object to another position. **(At this point the bug will occur)**

**Comment by easylogic** [comment]
hi @danielmalencar  

I checked this issue.  

I will fix it today.

**Comment by easylogic** [comment]
I fixed this problem. 

Please test it again.

**Comment by danielmalencar** [comment]
The problem was only solved when dragging holding the name of the object. But when you drag while holding the object itself it returns to the initial shape

**Comment by danielmalencar** [comment]
Try to drag the object without clicking on its name. The problem will occur.

**Comment by easylogic** [comment]
Can you show me  a video capture about this issue?

**Comment by danielmalencar** [comment]
Yes. A moment, please.

**Comment by danielmalencar** [comment]
[2020-09-28 00-20-56.zip](https://github.com/easylogic/editor/files/5289760/2020-09-28.00-20-56.zip)

**Comment by easylogic** [comment]
Thanks @danielmalencar  

I found it at firefox.  

I will check it again.

**Comment by danielmalencar** [comment]
I tested in  Opera

**Comment by easylogic** [comment]
ok, i will  test it in Opera too.

**Comment by easylogic** [comment]
@danielmalencar  

I fixed this issue.  

Please check it .

**Comment by danielmalencar** [comment]
Thanks! Now it works
