### ISSUE TITLE
Incorrect Bounds After Editing Points

### ISSUE THREAD

**Issue by danielmalencar** [easylogic/editor#81]
Incorrect selection bounds after editing points
![imagem_2020-09-28_124016](https://user-images.githubusercontent.com/25048796/94454022-c313ce80-0187-11eb-90ee-16b8f3628e74.png)

**Comment by easylogic** [comment]
This form is basically a spec. However, there are many concerns. Since the current editor is an HTML based editor, I am thinking about how to handle the SVG Path area. Currently, a small area is considered a canvas and a path is set.

If you have a good opinion, it would be nice to let me know.

**Comment by danielmalencar** [comment]
It may be better not to display the selection area for this type of object

**Comment by danielmalencar** [comment]
just keep higlight

**Comment by easylogic** [comment]
Thanks for the good comment. Let's consider again how to handle path.

**Comment by easylogic** [comment]
I am implementing to path bounding.  

![ezgif com-gif-maker](https://user-images.githubusercontent.com/591983/100834811-e4f33f80-34af-11eb-9825-279d78b65b6c.gif)

**Comment by easylogic** [comment]
I released this.  
Please test it on https://editor.easylogic.studio
