### ISSUE TITLE
 Timeline suggestion

### ISSUE THREAD

**Issue by danielmalencar** [easylogic/editor#83]
A suggestion: 
the top of the timeline could be resizable, as it covers much of the screen, so it’s unpleasant to create animations

**Comment by easylogic** [comment]
ok,  

I'll put a function to adjust the height of the timeline by dragging.

**Comment by easylogic** [comment]
hi @danielmalencar 

I  add a feature that  support resizable footer height.

**Comment by danielmalencar** [comment]
Very good!
