### ISSUE TITLE
Image don't show

### ISSUE THREAD

**Issue by danielmeloalencar** [easylogic/editor#96]
When you add an image it displays normally, but when you click Select a Image and choose an image it does not load.

![imagem_2020-12-17_182046](https://user-images.githubusercontent.com/74947997/102545125-94c1d300-4094-11eb-808d-cc87d8dec423.png)

**Comment by easylogic** [comment]
@danielmeloalencar 

I will check it.   Thanks.

**Comment by easylogic** [comment]
@danielmeloalencar 

I fixed this issue.

Please test it on https://editor.easylogic.studio
