### ISSUE TITLE
Initial artboard position

### ISSUE THREAD

**Issue by danielmeloalencar** [easylogic/editor#97]
Artboard doesn't start centralized, this is annoying, mainly because it doesn't have a pan feature.

![imagem_2020-12-18_180443](https://user-images.githubusercontent.com/74947997/102661409-812d6f80-415b-11eb-9b51-3317ed8202fc.png)

**Comment by danielmeloalencar** [comment]
My screen resolution es 1360x768

**Comment by easylogic** [comment]
@danielmeloalencar  

I added feature to reposition  selection area. 

Shortcut is not yet. 
If you want shortcut, please tell me.

<img width="176" alt="스크린샷 2020-12-30 오전 12 20 36" src="https://user-images.githubusercontent.com/591983/103294275-e5421480-4a34-11eb-9b0a-126601964374.png">

**Comment by easylogic** [comment]
hi @danielmeloalencar  

When the screen first comes up, the artboard is set to be centered.
